server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/shopapp
    username: root
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true

  #config file and multipart file
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: /api/v1
app:
  max:
    image:
      size: 10485760
    images:
      per-product: 5